---
- name: Install nginx
  become: true
  apt:
    name: 
      - nginx=1.18.0* 
    update_cache: true
- name: "Allow all access to tcp port {{ hostport }}"
  become: true
  ufw:
    rule: allow
    port: '{{ hostport }}'
    proto: tcp
- name: Configure auto start nginx
  become: true
  command: "systemctl enable nginx"  
  notify: 
    - Start nginx service
